# Dataset directories
data_dir: 'data'
train_dir: '/import/c4dm-datasets/MAPS_working'
# val_dir: 'data/valid'
val_dir: '/import/c4dm-datasets/MAPS_working'

# Model input parameters
arch: 'fpaint'
fs: 16000
dur: 16.38
norm: 0.95
win_len: 400
hop_len: 128
n_fft: 512
hpf_pole: 0.98  # spectrogram enhancement
density: 1000.0
f_sd : 3.0   # how wide to spreak peaks
maxpksperframe: 256   # maximum number of peaks per frame
oversamp: 1  # oversample factor for peak detection
n_frames: 2048
silence: 0.0005  # silence threshold
lambda: 0.1  # weight for the R1 penalty


# Dataset and Model hyperparameters
train_sz: 15000
val_sz: 100
bsz_train: 32
tau: 0.05
lr: 9.0e-5
n_epochs: 100

