# Dataset directories
data_dir: 'data'
train_dir: '/import/c4dm-datasets/PiJAMA/data'
# val_dir: 'data/valid'
val_dir: '/import/c4dm-datasets/PiJAMA/data'

# Model input parameters
arch: 'fpaint'
fs: 16000
dur: 2.0475
norm: 0.95
win_len: 400
hop_len: 128
n_fft: 512
hpf_pole: 0.98  # spectrogram enhancement
density: 1000.0
f_sd : 30.0   # how wide to spreak peaks
maxpksperframe: 64  # maximum number of peaks per frame
oversamp: 1  # oversample factor for peak detection
n_frames: 2048
silence: 0.0005  # silence threshold
lambda: 0.1  # weight for the R1 penalty


# Dataset and Model hyperparameters
train_sz: 2700
val_sz: 50
bsz_train: 16
tau: 0.05
d_lr: 5.0e-5
g_lr: 1.0e-4
n_epochs: 100

